"""Step 8: final dataset statistics and README_DATASET_V4.txt."""

from __future__ import annotations

from pathlib import Path

import pandas as pd

from .common import (
    StepResult,
    as_bool,
    load_index,
    print_summary,
    save_csv,
    setup_logging,
    write_step_summary,
)
from .settings import Settings


def _count_tree(root: Path, settings: Settings) -> pd.DataFrame:
    rows = []
    if not root.exists():
        return pd.DataFrame(columns=["split", "lesion_type", "risk_label", "count"])
    for split in settings.splits:
        for lesion in settings.lesion_types:
            for risk in settings.risk_levels:
                folder = root / split / lesion / risk
                n = 0
                if folder.exists():
                    n = sum(
                        1
                        for p in folder.iterdir()
                        if p.is_file() and p.suffix.lower() in settings.valid_extensions
                    )
                rows.append({"split": split, "lesion_type": lesion, "risk_label": risk, "count": n})
    return pd.DataFrame(rows)


def _original_counts(df: pd.DataFrame, settings: Settings) -> pd.DataFrame:
    rows = []
    for split in settings.splits:
        for lesion in settings.lesion_types:
            for risk in settings.risk_levels:
                n = int(
                    (
                        (df["split"] == split)
                        & (df["lesion_type"] == lesion)
                        & (df["current_risk_label"] == risk)
                    ).sum()
                )
                rows.append({"split": split, "lesion_type": lesion, "risk_label": risk, "count": n})
    return pd.DataFrame(rows)


def _format_counts(title: str, counts: pd.DataFrame, settings: Settings) -> str:
    lines = [title]
    for split in settings.splits:
        lines.append(f"{split.capitalize()}:")
        for lesion in settings.lesion_types:
            lines.append(f"  {lesion.capitalize()}:")
            for risk in settings.risk_levels:
                match = counts[
                    (counts["split"] == split)
                    & (counts["lesion_type"] == lesion)
                    & (counts["risk_label"] == risk)
                ]
                n = int(match["count"].iloc[0]) if not match.empty else 0
                lines.append(f"    {risk} = {n}")
        lines.append("")
    return "\n".join(lines)


def write_readme(settings: Settings, stats: dict, original: pd.DataFrame, final: pd.DataFrame) -> str:
    text = f"""Skin_Risk_Dataset_V4
====================

This file is generated by the cleaning pipeline. It describes the rebuilt
dataset, not a promise of a particular accuracy.

Dataset structure
-----------------
{settings.final_dataset_name}/
  train|val|test /
    acne|burns|rash|warts /
      Low|Medium|High /
        <images>

Target labels for training: Low, Medium, High.
Lesion type is preserved in the folder tree so you can train a risk-only
model or a multi-task / hierarchical model.

Cleaning process
----------------
1. Recursive validation of folders, extensions, readability, and dimensions.
2. Exact duplicate detection (file SHA-256 and decoded-pixel SHA-256).
3. Near-duplicate detection (perceptual pHash / dHash).
4. Quality scoring (blur, exposure, contrast, entropy, resolution).
5. Within-lesion risk-label consistency checks. Medium images similar to
   Low or High were flagged. No automatic relabelling was performed.
6. Questionable images were copied into Review/ for manual inspection.
7. A leakage-free stratified rebuild (approximately 70% / 15% / 15%).

Splitting method
----------------
- Random seed: {settings.seed}
- Approximate ratios: train={settings.train_ratio:.0%}, val={settings.val_ratio:.0%}, test={settings.test_ratio:.0%}
- Stratified by lesion type AND risk level.
- Near-duplicate groups are atomic: every member stays in the same split.
- Exact duplicates: one representative kept.
- Essentially identical near-duplicates (Hamming <= {settings.exact_near_threshold}) : one kept.

Duplicate handling
------------------
Exact duplicates cannot appear in more than one split because only one
file is copied into V4. Near-duplicates that remain are assigned together
so a resized/cropped/recompressed copy cannot leak across train/val/test.

Quality checks
--------------
Low-quality and corrupted images are reported in quality_report.csv and
copied into Review/. They are not blindly deleted. Unreviewed CHECK_QUALITY
and CHECK_LABEL items are held out of V4 when exclude_unreviewed_flags=true.

Class counts
------------
{_format_counts("Original dataset (before cleaning):", original, settings)}
{_format_counts("Skin_Risk_Dataset_V4 (after cleaning and resplit):", final, settings)}

Summary counts
--------------
Original images scanned : {stats.get("total_original_images")}
Final V4 images         : {stats.get("total_final_images")}
Removed / held out      : {stats.get("images_removed")}
Exact duplicate images  : {stats.get("exact_duplicates_detected")}
Near-duplicate images   : {stats.get("near_duplicates_detected")}
Corrupted images        : {stats.get("corrupted_images_detected")}
Low-quality flagged     : {stats.get("low_quality_images_detected")}
Ambiguous labels        : {stats.get("ambiguous_images_detected")}
Manual review required  : {stats.get("images_requiring_manual_review")}

Risk-label limitations
----------------------
Low / Medium / High risk is a clinical judgement. Two photographs can look
similar and still have different risk, or look different and have the same
risk. The previous model confused Medium with both Low and High; that often
means the visual boundary is genuinely weak, not only that the split was
leaky.

This pipeline NEVER auto-relabels risk from image similarity. Ambiguous
samples are in Review/ambiguous_labels/ and reports/ambiguous_samples.csv.
If, after clinical review, many Medium images cannot be distinguished from
Low or High by appearance alone, that limitation should be reported. Do not
force a 90%+ test accuracy by leaking test images or rewriting labels.

Known limitations
-----------------
- Perceptual hashing finds many near-duplicates but can miss aggressive
  crops, overlays, or heavy color grading.
- "Lesion not visible" cannot be certified without a clinician or a
  dedicated detection model. Extreme low-information frames are flagged.
- Horizontal flips may be inappropriate for laterality-sensitive sites.
- Balancing is NOT done by duplicating images. Prefer class weights and
  train-time augmentation. See pipeline/augmentation.py and train_v4.py.
- Validation and test images must never be augmented or used for training.

Scientific rules
----------------
- Original dataset is untouched.
- Test images were not mixed into training.
- Test labels were not used to rewrite training labels.
- Final test set should stay unseen until a single end-of-project evaluation.

Supporting files
----------------
reports/dataset_manifest.csv
reports/dataset_statistics.csv
reports/duplicates_report.csv
reports/near_duplicates_report.csv
reports/ambiguous_samples.csv
reports/quality_report.csv
reports/review.csv
reports/leakage_report.csv
reports/excluded_from_v4.csv
"""
    path = settings.output_root / "README_DATASET_V4.txt"
    path.write_text(text, encoding="utf-8")
    (settings.final_dir / "README_DATASET_V4.txt").write_text(text, encoding="utf-8")
    return str(path)


def generate_statistics(settings: Settings) -> StepResult:
    logger = setup_logging(settings)
    df = load_index(settings)
    if df.empty:
        raise RuntimeError("Image index is empty. Run earlier steps first.")

    original = _original_counts(df, settings)
    final = _count_tree(settings.final_dir, settings)

    def _bool_sum(col: str) -> int:
        if col not in df.columns:
            return 0
        return int(df[col].map(as_bool).sum())

    review_needed = 0
    if "recommended_action" in df.columns:
        review_needed = int((~df["recommended_action"].fillna("KEEP").isin(["KEEP", "keep"])).sum())

    stats = {
        "total_original_images": int(len(df)),
        "total_final_images": int(final["count"].sum()) if not final.empty else 0,
        "images_removed": int(len(df) - (final["count"].sum() if not final.empty else 0)),
        "exact_duplicates_detected": _bool_sum("is_exact_duplicate"),
        "near_duplicates_detected": _bool_sum("is_near_duplicate"),
        "corrupted_images_detected": _bool_sum("is_corrupted"),
        "low_quality_images_detected": _bool_sum("is_low_quality"),
        "ambiguous_images_detected": _bool_sum("is_ambiguous"),
        "images_requiring_manual_review": review_needed,
        "seed": settings.seed,
        "final_dataset": str(settings.final_dir),
    }

    rows = [{"metric": key, "value": value} for key, value in stats.items()]
    for _, row in original.iterrows():
        rows.append(
            {
                "metric": f"original.{row['split']}.{row['lesion_type']}.{row['risk_label']}",
                "value": int(row["count"]),
            }
        )
    for _, row in final.iterrows():
        rows.append(
            {
                "metric": f"v4.{row['split']}.{row['lesion_type']}.{row['risk_label']}",
                "value": int(row["count"]),
            }
        )
    stats_path = save_csv(pd.DataFrame(rows), settings.reports_dir / "dataset_statistics.csv")
    readme_path = write_readme(settings, stats, original, final)

    print_summary("Final dataset statistics", stats)
    print()
    print(_format_counts("Skin_Risk_Dataset_V4 counts:", final, settings))
    result = StepResult("08_statistics", stats, [str(stats_path), readme_path])
    write_step_summary(settings, result)
    logger.info("Statistics written to %s", stats_path)
    return result
